from typing import Protocol

from app.core.task import Task


class TaskRepository(Protocol):
    def list(self) -> list[Task]: ...
    def get(self, task_id: int) -> Task | None: ...
    def save(self, task: Task) -> Task: ...
    def delete(self, task_id: int) -> None: ...
